on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Renpy Project
      uses: ProjectAliceDev/renpy-build-action@master
      with:
        sdk-version: '8.1.3'
        project-dir: 'renpy-builds'
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy